### ISSUE TITLE
Deformed PDB files produced with PDBFixer

### ISSUE THREAD

**Issue by jchodera** [pandegroup/pdbfixer#92]
`pdbfixer` seems to produce a highly deformed structure for PDB id code `1AO7`.

You can reproduce this yourself by running the HTML-based `pdbfixer` on `1AO7` to simply build in the hydrogens.  For some reason, they end up with all sorts of crazily acute angles (see images).

Any idea why this is?  I haven't seen this happen before...
![deformed-1](https://cloud.githubusercontent.com/assets/3656088/8264732/f845b39a-16b7-11e5-9c7d-a1ed09ef849a.png)
![deformed-2](https://cloud.githubusercontent.com/assets/3656088/8264734/f9848768-16b7-11e5-858c-ea5a92689f21.png)
![deformed-3](https://cloud.githubusercontent.com/assets/3656088/8264735/fad4b386-16b7-11e5-8c12-55e676e06213.png)

Resulting PDB structure can be found here: [`pdbfixer-output.pdb`](https://gist.github.com/jchodera/cc7c83e4c26f8cc43815)

**Comment by jchodera** [comment]
Actually, I'm seeing this behavior with a lot of PDB files of this size...

**Comment by peastman** [comment]
I'd guess something's going wrong with the energy minimization.  It first adds hydrogens at fairly arbitrary positions, then runs an energy minimization with everything except hydrogens immobilized to fix them up.  But if the minimization fails for some reason, it will just return the original positions.

**Comment by jchodera** [comment]
Let's check to make sure this isn't still a problem before we cut a release.

**Comment by peastman** [comment]
It looks like the minimization wasn't failing.  The force just wasn't strong enough.  If you don't specify a ForceField when you call addHydrogens(), it makes up a potential designed to give vaguely plausible positions.  All the hydrogens repel each other (but only over very short distances), and there are also angle terms for a few special cases like water.  The force on the hydrogens wasn't large enough, and so the minimizer was exiting before they had moved enough.

The fix is trivial, but unfortunately it's in Modeller, not in PdbFixer.

**Comment by jchodera** [comment]
So we would need an OpenMM 6.3.1?

**Comment by peastman** [comment]
Yes, if we decide it's important enough.  Remember, as soon as you do a minimization with any real force field the problem will get fixed.

**Comment by jchodera** [comment]
This would seem to be useful for getting PDBFixer to work well as a
standalone tool.

Could the hydrogen force constants in PDBFixer be increased instead as a
workaround?

**Comment by peastman** [comment]
There are no hydrogen force constants in PDBFixer.  It just calls addHydrogens().

**Comment by ajasja** [comment]
@jchodera  @peastman  This is still present when using OpenMM 7.1.1

Couldn't PDBFixer just accept a forcefield? (and use Amber by default)

Input:
![image](https://user-images.githubusercontent.com/19926/34152515-26fd7124-e4af-11e7-923f-0ccf87fda6c1.png)

Output:
![image](https://user-images.githubusercontent.com/19926/34152533-30e830ca-e4af-11e7-9535-579c02aba935.png)

Script:
```python
pH = 7.5
fixer = pdbfixer.PDBFixer('NB26_APH.pdb')
forcefield = app.ForceField('amber99sbildn.xml', 'amber99_obc.xml')
fixer.findMissingResidues()
fixer.findNonstandardResidues()
fixer.replaceNonstandardResidues()
fixer.removeHeterogens(False)
fixer.findMissingAtoms()
fixer.addMissingAtoms()
fixer.addMissingHydrogens(pH)
with open("NB26_APH.fix.pdb", 'w') as outfile:
    app.PDBFile.writeFile(fixer.topology, fixer.positions, outfile)
```

**Comment by jchodera** [comment]
Could you upload your `NB26_APH.pdb` file so we can take a look? You'll probably have to ZIP it up.

**Comment by ajasja** [comment]
Sure, here it is:
[NB26_APH.zip](https://github.com/pandegroup/pdbfixer/files/1572080/NB26_APH.zip)
It contains a lot of lysins:)

**Comment by ajasja** [comment]
Minimization/simulation then fails. 

```python
from __future__ import print_function
from simtk.openmm import app
import simtk.openmm as mm
from simtk import unit
from sys import stdout

pdb = app.PDBFile('struct/NB26_APH.fix.pdb')
#forcefield = app.ForceField('amber99sbildn.xml',  'amber99_obc.xml')
#forcefield = app.ForceField('amber99sbildn.xml')
forcefield = app.ForceField('amber10.xml', 'amber10_obc.xml')
system = forcefield.createSystem(pdb.topology, nonbondedMethod=app.CutoffPeriodic, 
    nonbondedCutoff=1.6*unit.nanometers, constraints=None, rigidWater=True)
integrator = mm.LangevinIntegrator(300*unit.kelvin, 5.0/unit.picoseconds, 
    1.0*unit.femtoseconds)
integrator.setConstraintTolerance(0.00001)

platform = mm.Platform.getPlatformByName('OpenCL')
properties = {'OpenCLPrecision': 'mixed'}
simulation = app.Simulation(pdb.topology, system, integrator, platform, 
    properties)

simulation.context.setPositions(pdb.positions)

print('Minimizing...')
simulation.minimizeEnergy(maxIterations=100000)

positions = simulation.context.getState(getPositions=True).getPositions()
with open("struct/NB26_APH.min.pdb", 'w') as outfile:
    app.PDBFile.writeFile(simulation.topology, positions, outfile)

simulation.context.setVelocitiesToTemperature(300*unit.kelvin)
print('Equilibrating...')
simulation.step(1000)

simulation.reporters.append(app.DCDReporter('out/trajectory.dcd', 1000))
simulation.reporters.append(app.StateDataReporter(stdout, 1000, step=True, 
    potentialEnergy=True, temperature=True, progress=True, remainingTime=True, 
    speed=True, totalSteps=10000, separator='\t'))

print('Running Production...')
simulation.step(10000)
print('Done!')
```

![image](https://user-images.githubusercontent.com/19926/34203152-613fab60-e57a-11e7-981b-19166b056856.png)

**Comment by jchodera** [comment]
I just ran your script with the OpenMM 7.2.0 beta and the corresponding `pdbfixer`, and things look fine:
![fixed](https://user-images.githubusercontent.com/3656088/34215637-0a7d5a4e-e574-11e7-9fc5-9bc8156e405b.png)
Can you try again after upgrading to these versions?

If you're using conda:
```bash
conda install --yes -c omnia/label/beta openmm==7.2.0 pdbfixer
```
Let us know if that works for you. If you still have trouble, I wonder if this might be a platform-specific issue.

**Comment by jchodera** [comment]
P.S. Your renderings look beautiful! Did you use VMD to generate those?

**Comment by ajasja** [comment]
Hi!

Thanks, that's done using [Chimera ](https://www.cgl.ucsf.edu/chimera/)(which is very beautiful by default:)

The problem remains using OpenMM 7.2 and pdbfixer 1.4-py35_0.

Fixed:
![image](https://user-images.githubusercontent.com/19926/34217579-1d03a316-e5ac-11e7-9da3-0572b094d15b.png)

Minimized:
![image](https://user-images.githubusercontent.com/19926/34217597-29a34b94-e5ac-11e7-8219-d6e2a076bd3a.png)
PS: why is minimization not working?

Script:
[Nb26-APH.zip](https://github.com/pandegroup/pdbfixer/files/1576319/Nb26-APH.zip) also [here](https://pastebin.com/3y4qPvQP).

**Comment by jchodera** [comment]
The latest pdbfixer is 1.5. Try forcing upgrade with:
```bash
conda install --yes -c omnia/label/beta openmm==7.2.0 pdbfixer==1.5
```
If this still fails, it *could* be that it's trying to use the GPU and the minimization isn't making progress due to restricted precision.

@peastman: Is there a way to force the CPU platform to be used in `pdbfixer`?

**Comment by ajasja** [comment]
Updated pdbfixer to `1.5-py35heda29b4_0 omnia/label/beta`

still the same result:

![image](https://user-images.githubusercontent.com/19926/34218283-16742942-e5ae-11e7-96f0-c670a399039b.png)

**Comment by jchodera** [comment]
It doesn't look like there's a way to specify the `Platform` to use in `pdbfixer`.

We'll need @peastman to help debug further.

**Comment by jchodera** [comment]
In the meantime, here's your fixed file!

[NB26_APH.fix.pdb.zip](https://github.com/pandegroup/pdbfixer/files/1576374/NB26_APH.fix.pdb.zip)

**Comment by ajasja** [comment]
Thanks! Although the simulation still crashes afterwards, even starting from the fixed file. 
The installation seems to be OK (can I run some more extensive tests?):

```
(ommprotocol) D:\data\MD\Nanobodies\Nb26-APH>python -m simtk.testInstallation
There are 3 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 OpenCL - Successfully computed forces

Median difference in forces between platforms:

Reference vs. CPU: 1.98179e-05
Reference vs. OpenCL: 2.15121e-05
CPU vs. OpenCL: 1.55429e-05
```

**Comment by jchodera** [comment]
Can you post your simulation script too?

**Comment by ajasja** [comment]
Sure:

```python
from simtk.openmm import app
import simtk.openmm as mm
from simtk import unit
from sys import stdout

pdb = app.PDBFile('struct/NB26_APH.jchodera.fix.pdb')
#forcefield = app.ForceField('amber99sbildn.xml',  'amber99_obc.xml')
#forcefield = app.ForceField('amber99sbildn.xml')
forcefield = app.ForceField('amber10.xml', 'amber10_obc.xml')
system = forcefield.createSystem(pdb.topology, nonbondedMethod=app.CutoffPeriodic, 
    nonbondedCutoff=1.6*unit.nanometers, constraints=None, rigidWater=True)
integrator = mm.LangevinIntegrator(300*unit.kelvin, 5.0/unit.picoseconds, 
    1.0*unit.femtoseconds)
integrator.setConstraintTolerance(0.00001)

platform = mm.Platform.getPlatformByName('OpenCL')
properties = {'OpenCLPrecision': 'mixed'}
simulation = app.Simulation(pdb.topology, system, integrator, platform, 
    properties)

simulation.context.setPositions(pdb.positions)

print('Minimizing...')
simulation.minimizeEnergy(maxIterations=100000)

positions = simulation.context.getState(getPositions=True).getPositions()
with open("struct/NB26_APH.min.pdb", 'w') as outfile:
    app.PDBFile.writeFile(simulation.topology, positions, outfile)

simulation.context.setVelocitiesToTemperature(300*unit.kelvin)
print('Equilibrating...')
simulation.step(1000)

simulation.reporters.append(app.DCDReporter('out/trajectory.dcd', 1000))
simulation.reporters.append(app.StateDataReporter(stdout, 1000, step=True, 
    potentialEnergy=True, temperature=True, progress=True, remainingTime=True, 
    speed=True, totalSteps=10000, separator='\t'))

print('Running Production...')
simulation.step(10000)
print('Done!')

**Comment by jchodera** [comment]
This explodes for me on the `CPU` platform with and without HBond constraints. Minimization seems to make progress, so I'm not quite sure what's going on here.

**Comment by ajasja** [comment]
Should I move this to a separate issue on the OpenMM github tracker?

**Comment by jchodera** [comment]
I think we should keep it here and figure out what's going on---I do suspect it might be something we can improve with `pdbfixer`.

**Comment by jaimergp** [comment]
I got it to work by changing the forcefield to `forcefield = app.ForceField('amber99sbildn.xml',  'amber99_obc.xml')` (first commented out line).

```python
from simtk.openmm import app
import simtk.openmm as mm
from simtk import unit
from sys import stdout

pdb = app.PDBFile('struct/NB26_APH.jchodera.fix.pdb')
forcefield = app.ForceField('amber99sbildn.xml',  'amber99_obc.xml')
#forcefield = app.ForceField('amber99sbildn.xml')
#forcefield = app.ForceField('amber10.xml', 'amber10_obc.xml')
system = forcefield.createSystem(pdb.topology, nonbondedMethod=app.CutoffPeriodic,
    nonbondedCutoff=1.6*unit.nanometers, constraints=None, rigidWater=True)
integrator = mm.LangevinIntegrator(300*unit.kelvin, 5.0/unit.picoseconds,
    1.0*unit.femtoseconds)
integrator.setConstraintTolerance(0.00001)

platform = mm.Platform.getPlatformByName('OpenCL')
properties = {'OpenCLPrecision': 'mixed'}
simulation = app.Simulation(pdb.topology, system, integrator, platform,
    properties)

simulation.context.setPositions(pdb.positions)

print('Minimizing...')
simulation.minimizeEnergy(maxIterations=100000)

positions = simulation.context.getState(getPositions=True).getPositions()
with open("struct/NB26_APH.min.pdb", 'w') as outfile:
    app.PDBFile.writeFile(simulation.topology, positions, outfile)

simulation.context.setVelocitiesToTemperature(300*unit.kelvin)
print('Equilibrating...')
simulation.step(1000)

simulation.reporters.append(app.DCDReporter('out/trajectory.dcd', 1000))
simulation.reporters.append(app.StateDataReporter(stdout, 1000, step=True,
    potentialEnergy=True, temperature=True, progress=True, remainingTime=True,
    speed=True, totalSteps=10000, separator='\t'))

print('Running Production...')
simulation.step(10000)
print('Done!')
```

Result (converted to single PDB trajectory with MDTraj): [traj.pdb.zip](https://github.com/pandegroup/pdbfixer/files/1579595/traj.pdb.zip)

**Comment by jchodera** [comment]
Interesting! I wonder why we're having trouble with `amber10`.

@peastman : Any ideas? Hydrogens without LJ centers?

**Comment by ajasja** [comment]
Jup, that works for me as well (on windows).

**Comment by peastman** [comment]
No idea.  It may just be random.  Any tiny perturbation to the minimization process can change where it ends up.

**Comment by jchodera** [comment]
@peastman: Minimization worked fine on my machine with CPU, but Dynamics NaNd with any timesteps I tried.

**Comment by peastman** [comment]
> Minimization worked fine on my machine with CPU

What does "worked fine" mean?  It appears to have left the system in a conformation that couldn't be simulated.

If it's blowing up immediately, you can generally tell where the problem is.  Just check which atoms have large forces on them.

**Comment by jaysoma** [comment]
This issue is ten years old, so I measured whether it still exists rather than
adding another screenshot. It does.

I ran the original repro (1AO7) through the identical fixer pipeline twice on
current pdbfixer/OpenMM — once with `addMissingHydrogens(7.0)` on its default
path, once passing `forcefield=app.ForceField('amber14-all.xml')` — and scored
every X–H bond and H–X–Y angle in the outputs:

|                                | default (no forcefield) | amber14-all |
|--------------------------------|------------------------:|------------:|
| H atoms placed                 | 5,387                   | 5,387       |
| mean X–H length (Å)            | **1.192**               | 1.068       |
| X–H off ideal by >0.2 Å        | **143**                 | 0           |
| H–X–Y angles <80°              | **42**                  | 0           |
| worst angle                    | **63.6°** (MET5 CG–HG2) | —           |
| H···H contacts <1.5 Å          | 1                       | 5           |

So the mechanism @peastman identified in 2015 — the invented potential's forces
being too weak for the minimizer to pull hydrogens into place — is still
producing deformed geometry on the default path, and the `forcefield` parameter
(added since the 2017 discussion) fully resolves it when actually used. The
only regression in the forcefield run is a handful of close H···H contacts,
none clashing below 1.4 Å.

The scorer is ~150 lines of stdlib Python (no OpenMM dependency) and I'm happy
to PR it as a test, which would pin this behaviour either way.

Given the numbers, is the preferred fix (a) defaulting `addMissingHydrogens`
to a real forcefield, (b) strengthening the invented potential's force
constants upstream in Modeller, or (c) documenting that standalone use should
always pass a forcefield? Happy to submit whichever PR the maintainers prefer.
